/**
 *
 * @type {import('@remix-run/dev').AppConfig}
 */
module.exports = {
  ignoredRouteFiles: ["**/.*"],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "build/index.js",
  // publicPath: "/build/",
  serverDependenciesToBundle: [
    /^rehype.*/,
    /^remark.*/,
    /^unified.*/,
    /^unist.*/,
    /^hast.*/,
    /^mdast.*/,
    /^micromark.*/,
    /^markdown.*/,
    /^mdx.*/,
    /^estree.*/,
    /^character-.*/,
    /^vfile.*/,
    /^is-.*/,
    /^@mdx-js.*/,
    "node:path",
    "node:process",
    "node:timers/promises",
    "node:events",
    "node:fs",
    "node:worker_threads",
    "node:child_process",
    "node:timers",
    "node:buffer",
    "@mdx-js/mdx",
    "ccount",
    "comma-separated-tokens",
    "decode-named-character-reference",
    "fault",
    "html-whitespace-sensitive-tag-names",
    "space-separated-tokens",
    "stringify-entities",
    "bail",
    "property-information",
    "trough",
    "@fal-works/esbuild-plugin-global-externals",
    "p-queue",
    "p-timeout",
    "parse-entities",
    "periscopic",
    "zwitch",
  ],
}
