// https://react-svgr.com/docs/custom-templates/#use-with-cli
const template = (variables, { tpl }) => {
  // this file is automatically generated! do not edit

  return tpl`
${variables.imports};

${variables.interfaces};

const ${variables.componentName} = (${variables.props}) => (
  ${variables.jsx}
);

// for backwards-compat–
export const ReactComponent = ${variables.componentName}

${variables.exports};
`
}

module.exports = template
