export default {
  "/flow-token/available-wallets/": "/flow/flow-token/available-wallets",
  "/staking/": "/nodes/staking",
  "/cadence/tutorial/04-non-fungible-tokens/":
    "/cadence/tutorial/05-non-fungible-tokens-1",
  "/fusd/": "/flow/fusd",
  "/status/": "https://status.onflow.org/",
  "/fcl/tutorials/flow-app-quickstart/":
    "/tools/fcl-js/tutorials/flow-app-quickstart",
  "/flow-token/backers/": "/flow/flow-token/backers",
  "/node-operation/upcoming-sporks/": "/nodes/node-operation/upcoming-sporks",
  "/node-operation/upcoming-sporks": "/nodes/node-operation/upcoming-sporks",
  "/flow-cli/install/": "/tools/flow-cli/install",
  "/flow-port/": "/nodes/flow-port",
  "/flow-port": "/nodes/flow-port",
  "/access-api/": "/flow/access-api/",
  "/fcl/": "/tools/fcl-js",
  "/cadence/tutorial/03-fungible-tokens/":
    "/cadence/tutorial/06-fungible-tokens",
  "/flow-cli/": "/tools/flow-cli",
  "/cadence/tutorial/06-marketplace-compose/":
    "/cadence/tutorial/08-marketplace-compose",
  "/fusd/providers/": "/flow/fusd/providers",
  "/flow-token/": "/flow/flow-token",
  "/flow-cli/generate-keys/": "/tools/flow-cli/generate-keys",
  "/core-contracts/flow-token/": "/flow/core-contracts/flow-token",
  "/concepts/accounts-and-keys/": "/learn/concepts/accounts-and-keys",
  "/concepts/": "/learn/concepts",
  "/cadence/tutorial/05-marketplace-setup/":
    "/cadence/tutorial/07-marketplace-setup",
  "/emulator/": "/tools/emulator",
  "/emulator": "/tools/emulator",
  "/node-operation/spork/": "/nodes/node-operation/spork",
  "/node-operation/spork": "/nodes/node-operation/spork",
  "/concepts/accessing-testnet/": "/concepts/accessing-testnet",
  "/flow-token/faq/": "/flow/flow-token/faq",
  "/node-operation/node-roles/": "/node-operation/node-roles",
  "/node-operation/node-roles": "/node-operation/node-roles",
  "/faq/operators/": "/flow/faq/operators",
  "/node-operation/node-setup/": "/nodes/node-operation/node-setup",
  "/node-operation/node-setup": "/nodes/node-operation/node-setup",
  "/flow-token/concepts/": "/flow/flow-token/concepts",
  "/flow-token/concepts": "/flow/flow-token/concepts",
  "/fcl/reference/api/": "/tools/fcl-js/reference/api",
  "/dapp-development/mainnet-deployment/":
    "/flow/dapp-development/mainnet-deployment",
  "/flow-go-sdk/": "/tools/flow-go-sdk",
  "/faq/developers/": "/flow/faq/developers",
  "/sdks/": "/tools",
  "/flow-js-sdk/flow-app-quickstart/":
    "/tools/fcl-js/tutorials/flow-app-quickstart",
  "/vscode-extension/": "/tools/vscode-extension",
  "/tools/vscode-cadence": "/tools/vscode-extension",
  "/staking/technical-overview/": "/nodes/staking/technical-overview",
  "/node-operation/past-sporks/": "/nodes/node-operation/past-sporks",
  "/staking/schedule/": "/nodes/staking/schedule",
  "/flow-token/delivery/": "/flow/flow-token/delivery",
  "/flow-cli/create-accounts/": "/tools/flow-cli/create-accounts",
  "/fcl/flow-app-quickstart/": "/tools/fcl-js/tutorials/flow-app-quickstart",
  "/dapp-development/testnet-deployment/":
    "/flow/dapp-development/testnet-deployment",
  "/flow-cli/configuration/": "/tools/flow-cli/configuration",
  "/cadence/tutorial/07-resources-compose/":
    "/cadence/tutorial/10-resources-compose",
  "/concepts/storage/": "/learn/concepts/storage",
  "/concepts/transaction-signing/": "/learn/concepts/transaction-signing",
  "/core-contracts/non-fungible-token/":
    "/flow/core-contracts/non-fungible-token",
  "/flow-cli/send-transactions/": "/tools/flow-cli/send-transactions",
  "/node-operation/node-bootstrap/": "/nodes/node-operation/node-bootstrap",
  "/node-operation/node-bootstrap": "/nodes/node-operation/node-bootstrap",
  "/node-operation/": "/node-operation",
  "/http-api/": "/http-api",
  "/staking/rewards/": "/nodes/staking/schedule",
  "/dapp-development/smart-contracts/":
    "/flow/dapp-development/smart-contracts",
  "/flow-cli/deploy-project-contracts/":
    "/tools/flow-cli/deploy-project-contracts",
  "/flow-cli/deploy-project-contracts":
    "/tools/flow-cli/deploy-project-contracts",
  "/fusd/transactions/": "/flow/fusd/transactions",
  "/fusd/transactions": "/flow/fusd/transactions",
  "/core-contracts/": "/flow/core-contracts",
  "/fcl/reference/transactions/": "/tools/fcl-js/reference/transactions",
  "/fcl-js/reference/transactions/": "/tools/fcl-js/reference/transactions",
  "/kitty-items/": "/learn/kitty-items",
  "/flow-cli/account-add-contract/": "/tools/flow-cli/account-add-contract",
  "/dapp-development/deployment/": "/flow/dapp-development/deployment",
  "/dapp-development/in-dapp-payments/":
    "/flow/dapp-development/in-dapp-payments",
  "/flow-cli/execute-scripts/": "/tools/flow-cli/execute-scripts",
  "/fcl/reference/proving-authentication/":
    "/tools/fcl-js/reference/proving-authentication",
  "/bounties/": "/community/bounties",
  "/core-contracts/fungible-token/": "/flow/core-contracts/fungible-token",
  "/staking/epoch-terminology/": "/nodes/staking/epoch-terminology",
  "/dapp-development/flow-dapp-anatomy/":
    "/flow/dapp-development/flow-dapp-anatomy",
  "/concepts/variable-transaction-fees/":
    "/learn/concepts/variable-transaction-fees",
  "/flow-cli/get-accounts/": "/tools/flow-cli/get-accounts",
  "/fcl/packages/fcl/CHANGELOG/": "NA",
  "/intro/FAQ/": "/flow/faq",
  "/cadence/tutorial/08-voting/": "/cadence/tutorial/09-voting",
  "/flow-js-testing/": "/tools/flow-js-testing",
  "/dapp-development/dapp-infrastructure/":
    "/flow/dapp-development/dapp-infrastructure",
  "/staking/faq/": "/nodes/staking/faq",
  "/fcl/reference/configure-fcl/": "/tools/fcl-js/reference/configure-fcl",
  "/dapp-development/contract-testing/":
    "/flow/dapp-development/contract-testing",
  "/dapp-development/": "/flow/dapp-development",
  "/flow-cli/start-emulator/": "/tools/flow-cli/start-emulator",
  "/fcl/reference/user-signatures/": "/tools/fcl-js/reference/user-signatures",
  "/fcl-js/reference/user-signatures/":
    "/tools/fcl-js/reference/user-signatures",
  "/staking/unlocked-staking-guide/": "/nodes/staking",
  "/fcl/tutorials/flow-app-quickstart":
    "/tools/fcl-js/tutorials/flow-app-quickstart",
  "/flow-cli/get-transactions/": "/tools/flow-cli/get-transactions",
  "/fcl/reference/authentication/": "/tools/fcl-js/reference/authentication",
  "/staking/custody-providers/": "/nodes/staking/custody-providers",
  "/dapp-deployment/testnet-deployment/":
    "/flow/dapp-development/testnet-deployment",
  "/fcl/reference/scripts/": "/tools/fcl-js/reference/scripts",
  "/dapp-development/user-accounts-and-wallets/":
    "/flow/dapp-development/user-accounts-and-wallets",
  "/flow-cli/account-update-contract/":
    "/tools/flow-cli/account-update-contract",
  "/kitty-items/install/": "/learn/kitty-items/install",
  "/dapp-development/testnet-testing/":
    "/flow/dapp-development/testnet-testing",
  "/dapp-development/testnet-testing": "/flow/dapp-development/testnet-testing",
  "/flow-cli/get-events/": "/tools/flow-cli/get-events",
  "/dapp-deployment/mainnet-deployment/":
    "/flow/dapp-development/mainnet-deployment",
  "/flow-cli/get-blocks/": "/tools/flow-cli/get-blocks",
  "/flow-cli/account-remove-contract/":
    "/tools/flow-cli/account-remove-contract",
  "/dapp-deployment/": "/flow/dapp-development",
  "/node-operation/full-observer-node/":
    "/nodes/node-operation/full-observer-node",
  "/flow-cli/project-contracts/": "/tools/flow-cli/project-contracts",
  "/flow-cli/project-contracts": "/tools/flow-cli/project-contracts",
  "/core-contracts/locked-tokens/": "/flow/core-contracts/locked-tokens",
  "/core-contracts/locked-tokens": "/flow/core-contracts/locked-tokens",
  "/node-operation/monitoring-nodes/": "/nodes/node-operation/monitoring-nodes",
  "/node-operation/monitoring-nodes": "/nodes/node-operation/monitoring-nodes",
  "/sdk-guidelines/": "/tools/fcl-js/reference/sdk-guidelines",
  "/fcl/reference/discovery/": "/tools/fcl-js/reference/discovery",
  "/fcl/reference/discovery": "/tools/fcl-js/reference/discovery",
  "/flow-go-sdk/creating-accounts/": "/tools/flow-go-sdk/creating-accounts",
  "/flow-go-sdk/creating-accounts": "/tools/flow-go-sdk/creating-accounts",
  "/docs/slashing-conditions/": "nodes/staking/stake-slashing",
  "/flow-token/locked-account-setup/": "/flow/flow-token/locked-account-setup",
  "/fcl/api/": "/tools/fcl-js/reference/api",
  "/faq/backers/": "/flow/faq",
  "/node-operation/faq/": "/nodes/node-operation/faq",
  "/staking/stake-slashing/": "/nodes/staking/stake-slashing",
  "/staking/locked-staking-guide/": "/nodes/staking",
  "/core-contracts/nft-metadata/": "/flow/core-contracts/nft-metadata",
  "/flow-js-testing/install/": "/tools/flow-js-testing/install",
  "/flow-cli/sign-transaction/": "/tools/flow-cli/sign-transaction",
  "/flow-cli/build-transactions/": "/tools/flow-cli/build-transactions",
  "/flow-js-sdk/": "/tools/fcl-js",
  "/flow-cli/get-status/": "/tools/flow-cli/get-status",
  "/staking/epoch-preparation/": "/nodes/staking/epoch-preparation",
  "/staking/epoch-preparation": "/nodes/staking/epoch-preparation",
  "/flow-js-sdk/packages/fcl/": "/tools/fcl-js",
  "/flow-cli/security/": "/tools/flow-cli/security",
  "/flow-cli/security": "/tools/flow-cli/security",
  "/node-operation/machine-existing-operator/":
    "/nodes/node-operation/machine-existing-operator",
  "/docs/getting-started-1/": "/getting-started",
  "/flow-token/earn/": "/flow/flow-token/earn",
  "/flow-go-sdk/querying-transactions/": "/tools/flow-go-sdk",
  "/bounties/responsible-disclosure/": "/flow/bounties/responsible-disclosure",
  "/core-contracts/flow-fees/": "/flow/core-contracts/flow-fees",
  "/access-api": "/http-api",
  "/kitty-items/start/": "/learn/kitty-items/start",
  "/intro/playground-manual/": "/flow/intro/playground-manual",
  "/flow-cli/get-collections/": "/tools/flow-cli/get-collections",
  "/nft-marketplace/minting-nfts/": "/flow/nft-marketplace/minting-nfts",
  "/nft-marketplace/minting-nfts": "/flow/nft-marketplace/minting-nfts",
  "/access-api-rate-limits/": "/nodes/access-api-rate-limits",
  "/flow-js-testing/execute-scripts/": "/tools/flow-js-testing/execute-scripts",
  "/flow-js-testing/execute-scripts": "/tools/flow-js-testing/execute-scripts",
  "/flow-js-testing/emulator/": "/tools/flow-js-testing/emulator",
  "/flow-js-testing/emulator": "/tools/flow-js-testing/emulator",
  "/dapp-deployment/contract-testing/":
    "/flow/dapp-development/contract-testing",
  "/staking/staking-collection/": "/nodes/staking/staking-collection",
  "/staking/staking-collection": "/nodes/staking/staking-collection",
  "/fcl/packages/fcl/CHANGELOG": "/tools/fcl-js",
  "/flow-cli/send-signed-transactions/": "/tools/flow-cli/sign-transaction",
  "/flow-go-sdk/building-transactions/": "/tools/flow-go-sdk",
  "/flow-go-sdk/building-transactions": "/tools/flow-go-sdk",
  "/flow-go-sdk/generating-keys/": "/tools/flow-go-sdk",
  "/node-operation/db-encryption-existing-operator/":
    "/nodes/node-operation/db-encryption-existing-operator",
  "/flow-js-testing/contracts/": "/tools/flow-js-testing/contracts",
  "/flow-js-testing/accounts/": "/tools/flow-js-testing/accounts",
  "/flow-js-testing/accounts": "/tools/flow-js-testing/accounts",
  "/flow-go-sdk/querying-events/": "/tools/flow-go-sdk",
  "/staking/machine-account/": "/nodes/staking/machine-account",
  "/staking/staking-options/": "/nodes/staking/staking-options",
  "/flow-go-sdk/signing-transactions/": "/learn/concepts/transaction-signing",
  "/flow-cli/decode-keys/": "/tools/flow-cli/decode-keys",
  "/flow-go-sdk/transfer-flow/": "/tools/flow-go-sdk",
  "/intro/glossary/": "/flow/intro/glossary",
  "/flow-cli/complex-transactions/": "/tools/flow-cli/complex-transactions",
  "/kitty-items/modify/": "/learn/kitty-items/modify",
  "/dapp-deployment/testnet-testing/":
    "/flow/dapp-development/testnet-deployment",
  "/flow-go-sdk/sending-transactions/":
    "/tools/flow-js-testing/send-transactions",
  "/flow-js-testing/send-transactions/":
    "/tools/flow-js-testing/send-transactions",
  "/flow-js-testing/send-transactions":
    "/tools/flow-js-testing/send-transactions",
  "/docs/": "/",
  "/core-contracts/staking-contract-reference":
    "/flow/core-contracts/staking-contract-reference",
  "/core-contracts/staking-collection/":
    "/flow/core-contracts/staking-collection",
  "/flow-cli/account-staking-info/": "/tools/flow-cli/account-staking-info",
  "/kitty-items/update/": "/learn/kitty-items/update",
  "/docs/cadence/": "/cadence",
  "/devtools/emulator/": "/tools/emulator",
  "/flow-js-sdk/packages/fcl/CHANGELOG/": "/tools/fcl-js",
  "/concepts/transaction-lifecycle/": "/learn/concepts/transaction-lifecycle",
  "/flow-js-testing/init/": "/tools/flow-js-testing/init",
  "/flow-js-testing/jest-helpers/": "/tools/flow-js-testing/jest-helpers",
  "/staking/epoch-scripts-events/": "/nodes/staking/epoch-scripts-events",
  "/nft-marketplace/selling-nfts/": "/flow/nft-marketplace/selling-nfts",
  "/nft-marketplace/selling-nfts": "/flow/nft-marketplace/selling-nfts",
  "/fcl/packages/types/CHANGELOG/": "/tools/fcl-js",
  "/flow-js-testing/templates/": "/tools/flow-js-testing/templates",
  "/staking/events/": "/nodes/staking/epoch-scripts-events",
  "/staking/events": "/nodes/staking/epoch-scripts-events",
  "/nft-marketplace/handling-accounts/":
    "/flow/nft-marketplace/handling-accounts",
  "/nft-marketplace/handling-accounts":
    "/flow/nft-marketplace/handling-accounts",
  "/flow-cli/manage-configuration/": "/tools/flow-cli/manage-configuration",
  "/flow-go-sdk/querying-blocks/": "/tools/flow-go-sdk",
  "/flow-js-testing/flow-token/": "/tools/flow-js-testing/flow-token",
  "/flow-js-testing/flow-token": "/tools/flow-js-testing/flow-token",
  "/flow-js-testing/init": "/tools/flow-js-testing/init",
  "/fcl/tutorials": "/tools/fcl-js/tutorials/flow-app-quickstart",
  "/flow-token": "/flow/flow-token",
  "/flow-cli/project-app/": "/tools/flow-cli/project-app",
  "/flow-js-testing/structure/": "/tools/flow-js-testing/structure",
  "/flow-cli/signature-generate/": "/tools/flow-cli/signature-generate",
  "/fcl/packages/types/CHANGELOG": "/tools/fcl-js",
  "/fcl": "/tools/fcl-js",
  "/token/staking/": "/nodes/staking",
  "/staking/qc-dkg/": "/nodes/staking/qc-dkg",
  "/fcl/packages/sdk/readme/": "/tools/fcl-js",
  "/flow-js-testing/api/": "/tools/flow-js-testing/api",
  "/fcl/packages/fcl/": "/tools/fcl-js",
  "/docs/hello-world/": "/",
  "/faq/developers": "/flow/faq/developers",
  "/staking/staking-scripts-events/": "/nodes/staking/epoch-scripts-events",
  "/nft-marketplace/": "/flow/nft-marketplace",
  "/dapp-development/DappArchitectures/":
    "/flow/dapp-development/DappArchitectures",
  "/fusd/testnet/": "/fusd/transactions",
  "/nft-marketplace/building-blocks/": "/flow/nft-marketplace/building-blocks",
  "/flow-js-sdk/packages/types/": "/tools/fcl-js",
  "/staking/scripts/": "/nodes/staking/epoch-scripts-events",
  "/docs/non-fungible-tokens/": "",
  "/token/faq/": "",
  "/core-contracts/service-account/": "/flow/core-contracts/service-account",
  "/dapp-development/mainnet-account-setup/":
    "/flow/dapp-development/mainnet-account-setup",
  "/dapp-development/mainnet-account-setup":
    "/flow/dapp-development/mainnet-account-setup",
  "/flip-fest-winners/": "",
  "/node-operation/node-migration/": "/nodes/node-operation/node-bootstrap",
  "/node-operation/node-migration": "/nodes/node-operation/node-bootstrap",

  "/docs/visual-studio-code-extension/": "",
  "/core-contracts": "/flow/core-contracts",
  "/flow-cli/signature-verify/": "/tools/flow-cli/signature-verify",
  "/docs/visual-studio-code-extension": "",
  "/docs/json-cadence-spec.md": "",
  "/docs/quick-set-up-for-marketplace/": "",
  "/flow-cli": "/tools/flow-cli",
  "/fcl/tutorials/": "",
  "/token/delivery/": "",
  "/node-operation": "/nodes/node-operation",
  "/nft-marketplace/best-practices/": "",
  "/sdk-guidelines/ubiquitous-language/": "",
  "/dapp-development/NFT-drop-styles/":
    "/flow/dapp-development/NFT-drop-styles",
  "/flow-js-sdk/fcl/": "",
  "/docs/introduction/": "",
  "/community-updates/sep-16-2020/": "/community",
  "/flow-token/available-wallets": "",
  "/flow-cli/snapshot-save/": "/tools/flow-cli/snapshot-save",
  "/docs": "",
  "/docs/cli/": "",
  "/docs/setting-up-a-node/": "",
  "/flow-go-sdk/querying-accounts/": "",
  "/docs/fungible-tokens/": "",
  "/docs/emulator": "",
  "/kitty-items/next-steps/": "/learn/kitty-items/next-steps",
  "/bounties": "",
  "/staking/qc-dkg-scripts-events/": "/nodes/staking/epoch-scripts-events",
  "/staking/qc-dkg-scripts-events": "/nodes/staking/epoch-scripts-events",
  "/staking/locked-delegation-guide/": "",
  "/fcl/packages/types/": "",
  "/docs/debugging": "",
  "/fcl/packages/fcl/src/exec/query/": "",
  "/dapp-development": "/flow/dapp-development",
  "/install/": "",
  "/staking/unlocked-delegation-guide/": "",
  "/flow-go-sdk": "/tools/flow-go-sdk",
  "/intro/flow-token/": "",
  "/concepts/service-account/": "",
  "/docs/cadence": "/cadence",
  "/flow-js-testing/generator/": "/tools/flow-js-testing/generator",
  "/fcl/scripts/": "",
  "/docs/cadence-json-spec.md": "",
  "/token/staking/locked/transactions/": "",
  "/fusd": "",
  "/http-api": "",
  "/flow-js-testing/examples/": "",
  "/cadence/access-control/": "/cadence/language/access-control",
  "/templates/cadence/": "",
  "/community-updates/oct-6-2020/": "/community",
  "/protocol/access-api/": "",
  "/docs/composable-smart-contracts-marketplace": "",
  "/docs/glossary/": "",
  "/flow-js-testing/structure": "/tools/flow-js-testing/structure",
  "/flow-js-testing/types/": "/tools/flow-js-testing/types",
  "/fcl/reference": "",
  "/interaction/": "",
  "/flow-js-sdk/packages/types/CHANGELOG/": "",
  "/cadence/tutorial/03-fungible-tokens":
    "/cadence/tutorial/06-fungible-tokens",
  "/cadence/composite-types/": "",
  "/reference/api/": "",
  "/flow-js-sdk/packages/sdk/readme/": "",
  "/sdks": "",
  "/docs/composable-resources-kitty-hats/": "",
  "/cadence/development/": "",
  "/docs/faq": "",
  "/fcl/packages/sdk/src/config/readme/": "",
  "/flow-go-sdk/creating-accounts.": "",
  "/cadence/subtyping/": "",
  "/flow-js-testing/generator": "/tools/flow-js-testing/generator",
  "/staking": "/nodes/staking",
  "/dev-wallet/": "",
  "/fcl-js/config": "/tools/fcl-js/reference/api#configuration",
  "/fcl/flow-app-quickstart": "/tools/fcl-js/tutorials/flow-app-quickstart",
  "/fcl/reference/api": "/tools/fcl-js/reference/api",
  "/flow-js-testing": "/tools/flow-js-testing",
  "/faq/operators": "/flow/faq/operators",
  "/staking/locked-third-party-operator/": "",
  "/fcl/packages/fcl": "",
  "/fcl/reference/authentication": "/tools/fcl-js/reference/authentication",
  "/language/references/": "",
  "/cadence/tutorial/04-non-fungible-tokens":
    "/cadence/tutorial/05-non-fungible-tokens-1",
  "/flow-js-sdk": "",
  "/staking/epoch-terminology/staking/schedule/": "",
  "/fcl/reference/": "",
  "/cadence/type-inference/": "",
  "/flow-token/available-wallet/": "",
  "/node-operation/unstaked_access_node/": "",
  "/core-contracts/account-creation/": "",
  "/docs/non-fungible-tokens": "",
  "/support/flow-port/": "",
  "/wallets/blocto-integration/": "",
  "/cli/": "",
  "/concepts/mainnet/": "",
  "/docs/journey-of-a-transaction/": "",
  "/docs/node-roles/": "",
  "/fcl-js/": "/tools/fcl-js",
  "/fcl/packages/fcl/src/wallet-provider-spec/user-signature/": "",
  "/flow-go-sdk/sign-transaction/": "",
  "/flow-js-sdk/packages/fcl-react/CHANGELOG/": "",
  "/token/concepts/": "",
  "/404/": "/404",
  "/cadence/Cadence/": "",
  "/cadence/WASM/": "",
  "/concepts/flow-concepts/mainnet/": "",
  "/docs/genesis-bootstrapping/": "",
  "/docs/hello-world": "",
  "/fcI/tutorials/flow-app-quickstart/": "",
  "/fcl/tutorials/flow-app-quickstart/?zarsrc=30": "",
  "/fcl/tutorials/flow-app-quickstart/)/": "",
  "/flow-/": "",
  "/images/logo.png": "",
  "/node-operation/node-setup/Networking/": "",
  "/node-operation/past-sporks/),/": "",
  "/token/staking/locked/setup/": "",
  "/vscode-extension/en/": "",
  "/concepts": "/learn/concepts",
  "/faq/backers": "/flow/faq",
  "/status": "",
  "/emulator/CONTRIBUTING/": "",
  "/flow-port/staking-guide": "/nodes/flow-port/staking-guide",
  "/fcl/reference/proving-authentication":
    "/tools/fcl-js/reference/proving-authentication",
  "/fcl-js/reference/proving-authentication":
    "/tools/fcl-js/reference/proving-authentication",
  "/cadence/contracts/": "",
  "/flow-cli/initialize-configuration/configuration/":
    "/tools/flow-cli/initialize-configuration",
  "/staking/staking/schedule/": "",
  "/node-operation/past-sporks": "",
  "/intro/dapp-deployment/index/": "",
  "/cadence/index/": "",
  "/flow-cli/install": "/tools/flow-cli/install",
  "/cadence/accounts/": "/cadence/language/accounts",
  "/cadence/glossary/": "",
  "/flow-cli/configuration/project-contracts/":
    "/tools/flow-cli/project-contracts",
  "/node-operation/node-roles/node-bootstrap/": "",
  "/build-transactions/": "",
  "/cadence/interfaces/": "",
  "/cadence/resources/": "",
  "/flow-cli/start-emulator/initialize-configuration/": "",
  "/kitty-items": "",
  "/cadence/transactions/": "",
  "/cadence/type-safety/": "",
  "/nft-marketplace/fusd/": "",
  "/concepts/accessing-mainnet/": "",
  "/docs/accessing-flow-devnet/": "",
  "/flow-cli/instal/": "/tools/flow-cli/install",
  "/flow-js-testing/contracts/structure/": "",
  "/winners/": "",
  "/dapp-development/in-dapp-payments/n/":
    "/flow/dapp-development/in-dapp-payments",
  "/fcl/user-signature/": "",
  "/api-test/": "",
  "/cadence/json-ca/": "",
  "/cadence/tutorial/08-marketplace-setup/": "",
  "/concepts/Concepts/": "/learn/concepts",
  "/concepts/flow-concepts/devnet/": "",
  "/core-contracts/nonfungible-token/": "",
  "/dapp-development/mainnet-deployment":
    "/flow/dapp-development/mainnet-deployment",
  "/derp/": "",
  "/docs/access-api/": "",
  "/docs/node-bootstrapping/": "",
  "/docs/non-fungible-token/": "",
  "/docs/voting": "",
  "/fcl/packages/sdk/TRANSITIONS/": "",
  "/fcl/packages/types/README/": "",
  "/flow-cli/get-collections": "",
  "/flow-go-sdk/generating-keys": "",
  "/node-operation/faq": "",
  "/node-operation/guides/spork-practice/": "",
  "/node-operation/guides/starting-nodes/": "",
  "/tutorial/cadence/04-non-fungible-tokens/": "",
  "/access-api/transaction/": "",
  "/api/fcl/": "",
  "/cadence/language/json/": "",
  "/cadence/operators/": "",
  "/cadence/tutorial/02-hell/": "/cadence/tutorial/02-hello-world",
  "/cadence/tutorial/07-resource-compose/": "",
  "/cadene/": "",
  "/concepts/slashing/": "",
  "/concepts/token-staking/": "",
  "/concepts/transactions/": "/learn/concepts/transaction-signing",
  "/docs/fungible-tokens": "",
  "/docs/getting-started-1": "",
  "/docs/hello-worpub/": "",
  "/docs/hello-worquired/": "",
  "/docs/hello-worThe/": "",
  "/docs/hello-woruired/": "",
  "/docs/monitoring-node-health/": "",
  "/docs/node-keys/": "",
  "/docs/node-operation-consolidated-guide": "",
  "/docs/node-operation-consolidated-guide/": "",
  "/docs/voting/": "",
  "/fc/": "/tools/fcl-js",
  "/fcl-sj/api/": "/tools/fcl-js/reference/api",
  "/fcl/)/": "/tools/fcl-js",
  "/fcl/api/These/": "",
  "/fcl/packages/sdk/src/encode/README/": "",
  "/fcl/tutorials/flow-app-quickstart/Vue/": "",
  "/fd/tutorials/flow-app-quickstart/": "",
  "/flow-cl/instal/": "",
  "/flow-cli/instal1Transaction/": "",
  "/flow-cli/installDeploying/": "",
  "/flow-cli/installTransaction/": "",
  "/flow-cli/send-transactions/https:/docs.onflow.org/flow-cli/send-transactions/":
    "",
  "/flow-clinstal/github/": "",
  "/flow-go-sdk/ccbb/": "",
  "/flow-go-sdk/signing-transactions": "",
  "/flow-js-testing/README/": "",
  "/flow-js-testing/send-transactions/types/": "",
  "/https:/docs.onflow.org": "",
  "/node-operation/node-bootstrap/?q=cache:pMlnmGgrsAoJ:https://docs.onflow.org/node-operation/node-bootstrap/+&cd=3&hl=en&ct=clnk&gl=hk":
    "",
  "/node-operation/past-+sporks/": "",
  "/play/": "",
  "/protocol/core-contracts/": "",
  "/proxy_u/en-ru.ru.100e42f3-616a06e0-e26d4f88-74722d776562/https/docs.onflow.org/flow-port/":
    "",
  "/sdk/api/": "",
  "/search/": "",
  "/search/?q=cadance": "",
  "/sitemap.xml": "",
  "/social-cards/index.png": "",
  "/sPlease/": "",
  "/stakin/": "",
  "/statis/": "",
  "/support/flow-port/staking-guide/": "",
  "/tusd/transactions/": "",
  "/tutorial/cadence/00-introduction/": "",
  "/tutorial/cadence/07-resources-compose/": "",
  "/flow-cli/generate-keys": "/tools/flow-cli/generate-keys",
  "/templates/documentation/": "",
  "/fcl/reference/transactions": "/tools/fcl-js/reference/transactions",
  "/fcl/config/": "",
  "/fcl/reference/user-signatures": "/tools/fcl-js/reference/user-signatures",
  "/tutorials/flow-app-quickstart/": "",
  "/dapp-deployment": "/flow/dapp-development",
  "/fcl/reference/configure-fcl": "/tools/fcl-js/reference/configure-fcl",
  "/fcl/reference/scripts": "/tools/fcl-js/reference/scripts",
  "/fcl-js/reference/scripts": "/tools/fcl-js/reference/scripts",
  "/send-transactions/": "",
  "/flow-js-sdk/flow-app-quickstart": "",
  "/cadence/capability-based-access-control/": "",
  "/fcl/packages/types": "",
  "/kitty-items/upgrade/": "",
  "/nft-marketplace/fcl/reference/authentication/": "",
  "/concepts/accounts-and-keys": "/learn/concepts/accounts-and-keys",
  "/fcl/reference/config/": "",
  "/flow-cli/deploy-project-contracts/project-contracts/":
    "/tools/flow-cli/deploy-project-contracts",
  "/tutorial/01-first-steps/": "",
  "/flow-cli/create-accounts": "/tools/flow-cli/create-accounts",
  "/sdk-guidelines": "",
  "/vscode-extension": "",
  "/core-contracts/flow-token": "/flow/core-contracts/flow-token",
  "/reference/proving-authentication/": "",
  "/reference/scripts/": "",
  "/reference/transactions/": "",
  "/node-operation/spork-process/": "",
  "/core-contracts/non-fungible-token":
    "/flow/core-contracts/non-fungible-token",
  "/nft-marketplace/fcl/": "",
  "/signing-transactions/": "",
  "/CONTRIBUTING/": "",
  "/nft-marketplace": "",
  "/nft-marketplace/flow-token/": "",
  "/staking/staking-options": "/nodes/staking/staking-options",
  "/concepts/accessing-testnet": "/learn/concepts/accessing-testnet",
  "/concepts/transaction-signing": "/learn/concepts/transaction-signing",
  "/core-contracts/fusd/": "",
  "/sign-transaction/": "",
  "/staking/epoch-terminology": "/nodes/staking/epoch-terminology",
  "/accounts/": "",
  "/building-transactions/": "",
  "/fixtures/README.md": "",
  "/flow-cli/create-accounts/flow-cli/": "",
  "/flow-cli/create-accounts/flow-cli/create-accounts/": "",
  "/flow-cli/get-accounts": "/tools/flow-cli/get-accounts",
  "/flow-cli/project-app": "/tools/flow-cli/project-app",
  "/flow/": "",
  "/fusd/providers": "",
  "/kitty-items/run-testnet/": "",
  "/reference/user-signatures/": "",
  "/404.html": "/404",
  "/cadence/language/access-control": "",
  "/cadence/tutorial/05-marketplace-setup":
    "/cadence/tutorial/07-marketplace-setup",
  "/concepts/variable-transaction-fees":
    "/learn/concepts/variable-transaction-fees",
  "/contracts/": "",
  "/core-contracts/flow-id-table-staking/": "",
  "/faq/": "/flow/faq",
  "/fcl-js/api/": "/tools/fcl-js/reference/api",
  "/flow-js-testing/install": "/tools/flow-js-testing/install",
  "/http/an/": "",
  "/kitty-items/get-started/": "",
  "/kitty-items/run-locally/": "",
  "/cadence/tutorial/06-marketplace-compose":
    "/cadence/tutorial/08-marketplace-compose",
  "/cadence/type-annotations/": "",
  "/concepts/storage": "/learn/concepts/storage",
  "/dapp-development/user-accounts-and-wallets":
    "/flow/dapp-development/user-accounts-and-wallets",
  "/execute-scripts/": "",
  "/f/": "",
  "/flow-app-quickstart/": "",
  "/flow-cli/get-transactions": "/tools/flow-cli/get-transactions",
  "/flow-js-sdk/packages/fcl": "",
  "/nft-marketplace/access-api/": "",
  "/nft-marketplace/dapp-development/in-dapp-payments/": "",
  "/sending-transactions/": "",
  "/token/earn/": "",
  "/cadence/cadence/language/contracts/": "",
  "/cadence/language/index/": "",
  "/cadence/language/type-hierarchy": "",
  "/core-contracts/staking-collection":
    "/flow/core-contracts/staking-collection",
  "/dapp-development/flow-dapp-anatomy":
    "/flow/dapp-development/flow-dapp-anatomy",
  "/docs/tutorials/flow-app-quickstart/": "",
  "/emulator/CONTRIBUTING.md": "",
  "/faq/ttps:/github.com/onflow/cadence/issues/208/": "",
  "/flow-cli/account-add-contract": "/tools/flow-cli/account-add-contract",
  "/flow-cli/account-update-contract":
    "/tools/flow-cli/account-update-contract",
  "/flow-cli/create-accounts/flow-cli/account-add-contract/": "",
  "/flow-cli/create-accounts/flow-cli/account-remove-contract/": "",
  "/flow-cli/create-accounts/flow-cli/account-staking-info/": "",
  "/flow-cli/create-accounts/flow-cli/account-update-contract/": "",
  "/flow-cli/create-accounts/flow-cli/build-transactions/":
    "/tools/flow-cli/build-transactions",
  "/flow-cli/create-accounts/flow-cli/configuration/": "",
  "/flow-cli/create-accounts/flow-cli/deploy-project-contracts/": "",
  "/flow-cli/create-accounts/flow-cli/execute-scripts/": "",
  "/flow-cli/create-accounts/flow-cli/generate-keys/": "",
  "/flow-cli/create-accounts/flow-cli/get-accounts/": "",
  "/flow-cli/create-accounts/flow-cli/get-blocks/": "",
  "/flow-cli/create-accounts/flow-cli/get-collections/": "",
  "/flow-cli/create-accounts/flow-cli/get-events/": "",
  "/flow-cli/create-accounts/flow-cli/get-status/": "",
  "/flow-cli/create-accounts/flow-cli/get-transactions/": "",
  "/flow-cli/create-accounts/flow-cli/initialize-configuration/": "",
  "/flow-cli/create-accounts/flow-cli/install/": "",
  "/flow-cli/create-accounts/flow-cli/project-contracts/": "",
  "/flow-cli/create-accounts/flow-cli/security/": "",
  "/flow-cli/create-accounts/flow-cli/send-signed-transactions/": "",
  "/flow-cli/create-accounts/flow-cli/send-transactions/": "",
  "/flow-cli/create-accounts/flow-cli/sign-transaction/": "",
  "/flow-cli/create-accounts/flow-cli/start-emulator/": "",
  "/flow-cli/create-accounts/sitemap/sitemap-index.xml": "",
  "/flow-cli/create-accounts/status/": "",
  "/flow-cli/send-transactions": "/tools/flow-cli/send-transactions",
  "/flow-go-sdk/build-transaction/": "",
  "/flow-js-sdk/api/": "",
  "/flow-port/machine-account-address/": "",
  "/http/": "",
  "/nft-marketplace/cadence/": "",
  "/node-operation/upcoming-sporks.mdx": "",
  "/send-signed-transactions/": "",
  "/staking/epoch-events/": "",
  "/access-api-jsonrpc/": "",
  "/access-api-rate-limits": "",
  "/account/": "",
  "/account/0x98a22b6790892289/": "",
  "/action/refresh/": "",
  "/cadence/blob/marketplace-tutorial/cadence/tutorial/07-resources-compose/":
    "",
  "/cadence/crypto/": "",
  "/cadence/functions/": "",
  "/cadence/tutorial/non-fungible-tokens/":
    "/cadence/tutorial/05-non-fungible-tokens-1",
  "/community-updates/sep-16-2020": "/community",
  "/concept/": "/learn/concepts",
  "/concepts/accounts-and-keys.md": "/learn/concepts/accounts-and-keys",
  "/core-contracts/flow-fees": "/flow/core-contracts/flow-fees",
  "/core-contracts/fud-token/": "",
  "/design-patterns/": "",
  "/docs/getting-started/": "",
  "/fcl/packages": "",
  "/fcl/packages/sdk/src/response/README/": "",
  "/fcl/r/": "",
  "/fcl/reference/sdk-guidelines/#connect":
    "/tools/fcl-js/reference/sdk-guidelines",
  "/flow-cli/account-staking-info": "/tools/flow-cli/account-staking-info",
  "/flow-cli/deploy-project-contracts/security/": "",
  "/flow-cli/execute-scripts": "/tools/flow-cli/execute-scripts",
  "/flow-cli/get-blocks": "/tools/flow-cli/get-blocks",
  "/flow-cli/initialize-configuration":
    "/tools/flow-cli/initialize-configuration",
  "/flow-cli/inst/": "/tools/flow-cli/install",
  "/flow-client/account-add-contract/": "",
  "/flow-js-sdk/creating-accounts/": "",
  "/flow-js-sdk/packages/fcl/CHANGELOG": "",
  "/flow-js-sdk/packages/types": "",
  "/flow-js-sdk/querying-transactions/": "",
  "/flow-js-testing/api/structure/": "",
  "/flow-js-testing/contracts": "/tools/flow-js-testing/contracts",
  "/flow-sdk/": "",
  "/flow-token/earn": "",
  "/flow-token/staking/": "",
  "/flowsdk/": "",
  "/home/": "",
  "/locked-delegation-guide/": "",
  "/nft-marketplace/nft-marketplace/handling-accounts/": "",
  "/nft-marketplace/nft-marketplace/minting-nfts/": "",
  "/node-operation=/": "",
  "/node-operations/": "",
  "/node-setup/": "",
  "/onflow/cadence/blob/marketplace-tutorial/cadence/tutorial/07-resources-compose/":
    "",
  "/primer/": "",
  "/reference/discovery/": "",
  "/sdk/": "",
  "/staking/faq": "/nodes/staking/faq",
  "/staking/rewards": "",
  "/staking/schedule": "/nodes/staking/schedule",
  "/staking/staking-events/": "",
  "/status/rss/": "",
  "/token/": "",
  "/usdc/": "",
  "/vscode-extantion/": "",
  "/wallets/": "",
  "/xmlrpc.php": "",
  "/an/": "",
  "/api/": "",
  "/cadance/": "",
  "/cadence/anti-patterns": "",
  "/cadence/built-in-functions/": "",
  "/cadence/dragons/": "",
  "/cadence/json-cadence-spe/": "/cadence/json-cadence-spec",
  "/cadence/ñanguage/": "",
  "/cadence/restricted-types/": "",
  "/cadence/tut/": "",
  "/cadence/tutoria/": "/cadence/tutorial",
  "/cadence/tutorial/01-hello-world/": "/cadence/tutorial/02-hello-world",
  "/cadence/tutorial/06/": "/cadence/tutorial/06-fungible-tokens",
  "/cadence/tutorial/08-voting": "/cadence/tutorial/09-voting",
  "/candence.": "cadence",
  "/candence/": "",
  "/concepta/": "/learn/concepts",
  "/concepts/events/": "",
  "/concepts/flow-concepts/": "/learn/concepts",
  "/concepts/interaction/": "",
  "/concepts/transacti/": "/learn/concepts/transaction-signing",
  "/core-contarcts/": "/flow/core-contracts",
  "/core-contract/": "/flow/core-contracts",
  "/core-contracts/flow-storage-fees/": "",
  "/core-contracts/flow-storage-token/": "",
  "/core-contracts/flow-token/0x1654653399040a61/": "",
  "/core-contracts/flow-token/events/": "",
  "/core-contracts/flow-tokens/": "",
  "/core-contracts/flow-usd/": "",
  "/core-contracts/fusd-token/": "",
  "/core-contracts/non-git/": "",
  "/dapp-deployment/cadence/": "",
  "/dapp-deployment/testnet-testing": "",
  "/dapp-development/contract-testing":
    "/flow/dapp-development/contract-testing",
  "/dapp-development/smart-contracts": "/flow/dapp-development/smart-contracts",
  "/dapp-development/testnet-deployment":
    "/flow/dapp-development/testnet-deployment",
  "/discord/": "",
  "/doc/fungible-tokens/": "",
  "/docs/account-addresses/": "",
  "/docs/composable-smart-contracts-marketplace/": "",
  "/docs/debugging/": "",
  "/docs/s/": "",
  "/docs/starting-your-nodes/": "",
  "/emulator/development/": "",
  "/events/": "",
  "/extendtion-vscode/": "",
  "/fcl-js/reference/api/": "/tools/fcl-js/reference/api",
  "/fcl-js/reference/api": "/tools/fcl-js/reference/api",
  "/fcl/api": "/tools/fcl-js/reference/api",
  "/fcl/docs/": "",
  "/fcl/interactions/": "",
  "/fcl/packages/sdk": "",
  "/fcl/reference/api/getTransactionStatus/": "",
  "/fcl/reference/api/query/": "",
  "/fcl/reference/how-it-works/": "",
  "/fcl/reference/installation/": "",
  "/fcl/reference/introduction/": "",
  "/fcl/reference/query/": "",
  "/fcl/reference/script/": "/tools/fcl-js/reference/scripts",
  "/fcl/reference/sdk-guidelines/": "/tools/fcl-js/reference/sdk-guidelines",
  "/fcl/sdk/": "",
  "/fcl/tutorials/fcl/": "",
  "/fcl/tutorials/flow-app-quick-start/": "",
  "/fcl/tutorials/flow-app-quickstart.": "",
  "/fcll/": "",
  "/feed/": "",
  "/flips/20220503-interaction-templates.md": "",
  "/flow-cli/accounts/": "",
  "/flow-cli/build-transactions": "",
  "/flow-cli/configuration": "/tools/flow-cli/configuration",
  "/flow-cli/create-accounts/flow-cli/complex-transactions/": "",
  "/flow-cli/create-accounts/flow-cli/decode-keys/": "",
  "/flow-cli/create-accounts/flow-cli/manage-configuration/": "",
  "/flow-cli/create-accounts/flow-cli/project-app/": "",
  "/flow-cli/create-accounts/flow-cli/signature-generate/": "",
  "/flow-cli/create-accounts/flow-cli/signature-verify/": "",
  "/flow-cli/create-accounts/flow-cli/snapshot-save/": "",
  "/flow-cli/decode-keys": "",
  "/flow-cli/get-events": "",
  "/flow-cli/start-emulator": "",
  "/flow-fcl/": "",
  "/flow-go-sdk/building-transactionss/": "",
  "/flow-go-sdk/create-account/": "",

  "/flow-go-sdk/creating-accounts/https:/flow-view-source.com/testnet/tx/39cf6fa96bd8be8ae24f2f2f574895444f0a40e762e8a9410bf1814668cf6feb/":
    "",
  "/flow-go-sdk/querying-transactions": "",
  "/flow-go-testing/api/": "",
  "/flow-java-sdk/": "",
  "/flow-js-sdk/flow-app-quickstart/using-our-authcluster/": "",
  "/flow-js-sdk/signing-transactions/": "",

  "/flow-js-testing/api": "",
  "/flow-js-testing/basic/": "",
  "/flow-js-testing/contracts/init/": "",
  "/flow-js-testing/execute-scripts/init/": "",
  "/flow-js-testing/send-transactions/structure/": "",
  "/flow-js-testing/templates": "",
  "/flow-js/": "",
  "/flow-js/api/": "",
  "/flow-jvm-sdk/querying-transactions/": "",
  "/flow-token/available-/wallets/": "",
  "/flow-token/available-wallets/blocto/": "",
  "/flow-token/delivery": "",
  "/flow-token/locked-account-setup": "",
  "/flow-token/staking/locked/setup/": "",
  "/flow-token/staking/node-operators/": "",
  "/flow/status/": "",
  "/flowtoken/": "",
  "/fungible-tokens/": "",
  "/guides/dapp-deployment/testnet-deployment/": "",
  "/guides/node-operator/genesis-bootstrap/": "",
  "/htt/": "",
  "/http/an.html": "",
  "/https:/docs.onflow.org/https:/docs.onflow.org": "",
  "/intro/": "",
  "/intro/glossary": "",
  "/js-sdk/": "",
  "/js-testing/": "",
  "/js/": "",
  "/kitty-items/install": "",
  "/language/": "",
  "/mainnet-deployment/": "",
  "/nft-marketplace/flip-fest-winners/": "",
  "/nft-marketplace/flow-token/concepts/": "",
  "/node-bootstrap/": "",
  "/node-operation/db-encryption-existing-operator": "",
  "/node-operation/db-encryption-existing-operators/": "",
  "/node-operation/full-observer-node/past-sporks/": "",
  "/node-operation/full-observer-node/spork/": "",
  "/node-operation/guides/": "",
  "/node-operation/guides/genesis-bootstrap/": "",
  "/node-operation/not-setup/": "",
  "/node-operation/past-spork/": "",
  "/node-operation/pcoming-sporks/": "",
  "/node-operation/post-sporks/": "",
  "/node-operation/unstaked-access-node/": "",
  "/node-operators/": "",
  "/operator/": "",
  "/operator/node-roles": "",
  "/page-data/fcl/tutorials/page-data.json": "",
  "/pl.js": "",
  "/port/": "",
  "/protocol/": "",
  "/public/assets/social-bg.jpg": "",
  "/reference/": "",
  "/reference/api/transaction-statuses/": "",
  "/robots.txt": "",
  "/rss/": "",
  "/sdk-guidelines/ubiquitous-language": "",
  "/sdksi/": "",
  "/sfg/": "",
  "/sitemap/sitemap-index.html": "",
  "/slashing-conditions/": "",
  "/stake/delegate/": "",
  "/staking/epoch-scripts-events": "",
  "/staking/epoch-scripts/events/": "",
  "/staking/qc-dkg-events/": "",
  "/staking/rewyards/": "",
  "/staking/stake-slashing": "",
  "/staking/staking-options/staking/staking-collection/": "",
  "/staking/unlocked-delegation-guide": "",
  "/status/fee/": "",
  "/status/feed/": "",
  "/token/staking": "",
  "/token/staking/locked/node-operators": "",
  "/tutorial/01-first-steps": "",
  "/tutorial/cadence/03-fungible-tokens/": "",
  "/tutorials/fcl/flow-app-quickstart/": "",
  "/tutorials/fclflow-app-quickstart/": "",
  "/types/": "",
  "/ubiquitous-language/": "",
  "/updates/oct-6-2020/": "",
  "/usd/": "",
  "/zh/": "",
  "/cadence/tutorial/01-first-steps/": "/cadence/tutorial",
}
