import { ToolsPageProps } from "../../ui/design-system/src/lib/Pages/ToolsPage"

import {
  flowserTool,
  overflowTool,
  dotNetSDK,
  swiftSDK,
  rustSDK,
  httpSDK,
  jvmSDK,
  goSDK,
  fclSDK,
  cliTool,
  emulatorTool,
  jsTestingLibTool,
  cadutTool,
  faucetTool,
  rubySDK,
  elixirSDK,
  pythonSDK,
  dartSDK,
  phpSDK,
  flowScanTool,
  flowViewSourceTool,
  bigDipperTool,
  walletApiTool,
  eventIndexingTool,
  accountApiTool,
  flowMarketplaceMonitorTool,
  alchemyAccessTool,
  alchemyNFTTool,
  intellijTool,
  vsCodeTool,
  commandLineLinter,
  cdcWebpackPlugin,
} from "../../component-data/Tools"

export const data: ToolsPageProps = {
  tools: [
    cliTool,
    emulatorTool,
    jsTestingLibTool,
    overflowTool,
    flowserTool,
    cadutTool,
    faucetTool,
    intellijTool,
    vsCodeTool,
    commandLineLinter,
    cdcWebpackPlugin,
  ],
  sdks: [
    httpSDK,
    fclSDK,
    goSDK,
    pythonSDK,
    jvmSDK,
    rubySDK,
    dartSDK,
    dotNetSDK,
    phpSDK,
    swiftSDK,
    rustSDK,
    elixirSDK,
  ],
  apisAndServices: [
    walletApiTool,
    eventIndexingTool,
    accountApiTool,
    flowMarketplaceMonitorTool,
    alchemyAccessTool,
    alchemyNFTTool,
  ],
  explorers: [flowScanTool, flowViewSourceTool, bigDipperTool],
  contentNavigationItems: [
    {
      title: "Concepts",
      text: "Lorem ipsum dolor sit amet proin gravida lorem ipsum",
      link: "#",
      icon: "concepts",
    },
    {
      title: "Learn",
      text: "Lorem ipsum dolor sit amet proin gravida lorem ipsum",
      link: "#",
      icon: "learn",
    },
    {
      title: "Tools",
      text: "Lorem ipsum dolor sit amet proin gravida lorem ipsum",
      link: "#",
      icon: "tools",
    },
  ],
}
