/**
 * @type {import('@remix-run/dev').AppConfig}
 */
module.exports = {
  cacheDirectory: "./node_modules/.cache/remix",
  ignoredRouteFiles: [".*", "**/*.css", "**/*.test.{js,jsx,ts,tsx}"],
  serverDependenciesToBundle: [
    /^rehype.*/,
    /^remark.*/,
    /^unified.*/,
    /^unist.*/,
    /^hast.*/,
    /^mdast.*/,
    /^micromark.*/,
    /^markdown.*/,
    "mdx-bundler",
    "ccount",
    "character-entities",
    "comma-separated-tokens",
    "decode-named-character-reference",
    "fault",
    "html-whitespace-sensitive-tag-names",
    "space-separated-tokens",
    "stringify-entities",
    "bail",
    "property-information",
    "vfile",
    "@mdx-js/esbuild",
    "character-entities-legacy",
    "character-entities-html4",
    "trough",
    "vfile-message",
    "@fal-works/esbuild-plugin-global-externals",
  ],
};
