/**
 * @type {import('@remix-run/dev').AppConfig}
 */
module.exports = {
  cacheDirectory: "./node_modules/.cache/remix",
  ignoredRouteFiles: [".*", "**/*.css", "**/*.test.{js,jsx,ts,tsx}"],
  serverDependenciesToBundle: [
    /^rehype.*/,
    /^remark.*/,
    /^unified.*/,
    /^unist.*/,
    /^hast.*/,
    /^mdast.*/,
    /^micromark.*/,
    /^markdown.*/,
    /^mdx.*/,
    /^estree.*/,
    /^character-.*/,
    /^vfile.*/,
    /^is-.*/,
    /^@mdx-js.*/,
    "@mdx-js/mdx",
    "ccount",
    "comma-separated-tokens",
    "decode-named-character-reference",
    "fault",
    "html-whitespace-sensitive-tag-names",
    "space-separated-tokens",
    "stringify-entities",
    "bail",
    "property-information",
    "trough",
    "@fal-works/esbuild-plugin-global-externals",
    "p-queue",
    "p-timeout",
    "parse-entities",
    "periscopic",
    "zwitch",
  ],
};
