name: Lint
on:
  push:
    branches:
      - main
      - dev
  pull_request: {}

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - name: Install modules
        run: yarn install
      - name: Formatting
        working-directory: apps/flow-docs # TODO: format entire repo with prettier
        run: yarn format:check

  typescript:
    name: Typescript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - name: Install modules
        run: yarn install
      - name: Typescript
        run: yarn typescheck
